### ISSUE TITLE
Bug: Unused parameter "source"

### ISSUE THREAD

**Issue by sirnino** [packituz-gttz/dive-orb#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Orb version

packituz/dive@0.0.2

### Current behavior

If I set `docker-archive` as value for the parameter `source` I expect to be able to run an analysis over a tar file on the disk. Actually the orb code doesn't use the `source` parameter at all.

### Minimum reproduction config

```yml
docker-verify:
    steps:
      - dive/install
      - dive/check:
          source: docker-archive
          image: image.tar
```

The error logged in CircleCI is:

> Image Source: docker://image.tar
Fetching image... (this can take a while for large images)
Handler not available locally. Trying to pull 'image.tar'...
Using default tag: latest
